import './globals.css'
import type { Metadata } from 'next'
import { Roboto_Flex as Roboto } from 'next/font/google'
import SideBar from '@/components/SideBar'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-alt' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} z-0 flex overflow-x-hidden bg-black`}
      >
        <SideBar />
        {children}
      </body>
    </html>
  )
}
